sonar.projectKey=15soat-fase1
sonar.projectName=15SOAT Fase 1 - Workshop OS API
sonar.projectVersion=1.0

sonar.sources=app
sonar.tests=tests
sonar.exclusions=**/vendor/**,**/node_modules/**,public/**,storage/**,bootstrap/cache/**

sonar.php.coverage.reportPaths=coverage.xml
sonar.php.tests.reportPath=test-results.xml

sonar.sourceEncoding=UTF-8
